-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;


entity alu_control is
  port (
    func : in std_logic_vector(5 downto 0);
    --sel:in std_logic_vector(5 downto 0);
    alu_op :in std_logic_vector(3 downto 0);
    alu_ctr:out std_logic_vector(3 downto 0)-- result
  );
end alu_control;

architecture struct of alu_control is

component not_gate is port(   
    x   : in  std_logic;
    z   : out std_logic);
end component;

component or_gate is port(   
    x   : in  std_logic;
    y   : in  std_logic;
    z   : out std_logic);
end component;

component aluop_gate is port(
    aluop: in  std_logic_vector(3 downto 0);
    sel:  in std_logic_vector(3 downto 0);
    z   : out std_logic
  );
end component;

component op_gate is port(
    op  : in  std_logic_vector(5 downto 0);
    sel:  in std_logic_vector(5 downto 0);
    z   : out std_logic);
end component;

component and_gate is port(
    x: in  std_logic; 
    y: in  std_logic;
    z: out std_logic);
end component ;



signal op_0_out,op_1_out,op_2_out,op_3_out,op_4_out,op_5_out,op_6_out,op_7_out,op_8_out:std_logic;
signal or_0_out,or_1_out,or_2_out,or_3_out,or_4_out,or_5_out: std_logic;
signal and_2_out,and_3_out: std_logic;
signal aluop_0_out:std_logic;
begin

    op_0: op_gate port map(func,"000000",op_0_out);
    op_1: op_gate port map(func,"101011",op_1_out);
    or_0: or_gate port map(op_0_out,op_1_out,or_0_out);
    and_0: and_gate port map(or_0_out,alu_op(3),alu_ctr(3));
    
    op_2: op_gate port map(func,"000000",op_2_out);
    op_3: op_gate port map(func,"101010",op_3_out);
    or_1: or_gate port map(op_2_out,op_3_out,or_1_out);
    and_1: and_gate port map(or_1_out,alu_op(3),alu_ctr(2));
    
    op_4: op_gate port map(func,"100100",op_4_out);
    op_5: op_gate port map(func,"100101",op_5_out);
    or_2: or_gate port map(op_4_out,op_5_out,or_2_out);
    and_2: and_gate port map(or_2_out,alu_op(3),and_2_out);
    not_0: not_gate port map(and_2_out,alu_ctr(1));
    
    op_6: op_gate port map(func,"100000",op_6_out);
    op_7: op_gate port map(func,"100001",op_7_out);
    op_8: op_gate port map(func,"100100",op_8_out);
    
    or_3: or_gate port map(op_6_out,op_7_out, or_3_out);
    or_4: or_gate port map(op_8_out,or_3_out,or_4_out);
    and_3: and_gate port map(or_4_out,alu_op(3),and_3_out);
    aluop_0: aluop_gate port map(alu_op,"0010",aluop_0_out);
    or_5: or_gate port map(aluop_0_out,and_3_out,or_5_out);
    not_1: not_gate port map(or_5_out,alu_ctr(0));

end struct;



