-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;

entity aluop_gate is
  port (
    aluop: in  std_logic_vector(3 downto 0);
    sel:  in std_logic_vector(3 downto 0);
    z   : out std_logic
  );
end aluop_gate;

architecture dataflow of aluop_gate is

component mux is port(
    sel	  : in	std_logic;
    src0  :	in	std_logic;
    src1  :	in	std_logic;
    z	  : out std_logic);
end component;


component not_gate is port(   
    x   : in  std_logic;
    z   : out std_logic);
end component;

component and_gate is port(
    x: in  std_logic; 
    y: in  std_logic;
    z: out std_logic);
end component ;

signal op5_not,op4_not,op3_not,op2_not,op1_not,op0_not, and0_out, and1_out,and2_out,and3_out,mux5_out,mux4_out,mux3_out,mux2_out,mux1_out,mux0_out: std_logic;


begin


    not_3: not_gate port map(aluop(3),op3_not);
    not_2: not_gate port map(aluop(2),op2_not);
    not_1: not_gate port map(aluop(1),op1_not);
    not_0: not_gate port map(aluop(0),op0_not);
    


    mux_3: mux port map(sel(3),op3_not,aluop(3),mux3_out);
    mux_2: mux port map(sel(2),op2_not,aluop(2),mux2_out);
    mux_1: mux port map(sel(1),op1_not,aluop(1),mux1_out);
    mux_0: mux port map(sel(0),op0_not,aluop(0),mux0_out);


    
    and_2: and_gate port map(mux3_out,mux2_out,and1_out);
    and_1: and_gate port map(mux1_out,mux0_out,and2_out);
    
    and_0: and_gate port map(and1_out,and2_out,z);






end dataflow;
