-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;


entity full_adder is
   port (
    
    x     : in std_logic;
    y     : in std_logic;
    c   : in std_logic;
    cout  : out std_logic;
    z     : out std_logic
  );
end full_adder;

architecture structural of full_adder is

component and_gate is port(x,y: in  std_logic; z: out std_logic);
end component;

component or_gate is port(x,y: in  std_logic; z: out std_logic);
end component;

component xor_gate is port(x,y: in  std_logic; z: out std_logic);
end component;

signal xor0_out, and0_out, and1_out: std_logic;

begin
    
    xor0: xor_gate port map(x,y,xor0_out);
    xor1: xor_gate port map(xor0_out,c, z);
    and0: and_gate port map(x,y,and0_out);
    and1: and_gate port map(xor0_out, c, and1_out);
    
    or0:   or_gate  port map(and0_out,and1_out,cout);

end structural;