-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;

entity slt_1 is
  port (
    ctrl_0  : in std_logic;
    ctrl_1  : in std_logic;
    A    : in std_logic;
    B    : in std_logic;
    cout  : out std_logic;  
    overf    : out std_logic; 
    R     : out std_logic   -- result
  );
end slt_1;

architecture slt_1_struct of slt_1 is

signal not_0_out, adder_0_out, cout_out, not_1_out,overflow, set,setu: std_logic;

component xor_gate is port(x,y: in  std_logic; z: out std_logic);
end component;

component not_gate is port(x: in std_logic; z:out std_logic);
end component;

component full_adder is port(cin,x,y: in std_logic; cout,z: out std_logic);
end component;

component mux2 is port(	sel	  : in	std_logic;
	src0  :	in	std_logic;
	src1  :	in	std_logic;
	z	  : out std_logic);
end component;

begin
  not_0: not_gate port map(B, not_0_out);
  full_adder_0: full_adder port map(ctrl_0,A, not_0_out, cout_out, adder_0_out);
  not_1: not_gate port map(cout_out,setu);
  xor_0: xor_gate port map(ctrl_0,cout_out,overflow);
  xor_1: xor_gate port map(overflow,adder_0_out, set);
  mux2_0: mux2    port map(ctrl_1,set,setu,R);
  overf<=overflow;

end slt_1_struct;
